# ===================================================================
# JHipster Registry starts up and read this name and allocate to itself.
# All the other modules override this setting in the <module-name>-dev.yml file.
# All module specific settings also goes into those configuration files.
# This file's settings are overridden by the module-dev.yml file settings if present.
# If no configuration in these two files, then it will look at the application-dev.yml and
# then the application.yml files inside the module itself.
# ===================================================================
spring:
    application:
        name: jhipster-registry
        
management:
    security:
    context-path: /management
            
jhipster:
    security:
        authentication:
            jwt:
                secret: incidentmanager-develop-secret

logging:
    level:
        ROOT: DEBUG
        za.co.ajk: DEBUG
        io.github.jhipster: DEBUG
        io.grpc: ERROR
        com.google.cloud.pubsub.v1: ERROR
        
#
# This is the configuration that will determine how the Google Topics as configured.
#
pubsubmessagetype:
    modules:
        -
            application_module_name: SystemGatewayModule
            pub_sub_message_type: IncidentMessage
            topics_list: GenericTopic
        -
            application_module_name: SystemGatewayModule
            pub_sub_message_type: Generic
            topics_list: testTopic
    topics_required:
        topic_names: BillingTopic, GenericTopic, IncidentTopic, IntegrationTopic, InventoryTopic, LoggingTopic, NotificationTopic, SystemGatewayTopic, WorkflowTopic
    subscriptions:
        -
            application_module_name: BillingModule
            topic_name: BillingTopic
            subscription_name: BillingTopicSub
        -
            application_module_name: IncidentModule
            topic_name: IncidentTopic
            subscription_name: IncidentTopicSub
        -
            application_module_name: IntegrationModul
            topic_name: IntegrationTopic
            subscription_name: IntegrationTopicSub
        -
            application_module_name: InventoryModule
            topic_name: InventoryTopic
            subscription_name: InventoryTopicSub
        -
            application_module_name: LoggingModule
            topic_name: LoggingTopic
            subscription_name: LoggingTopicSub
        -
            application_module_name: NotificationModule
            topic_name: NotificationTopic
            subscription_name: NotificationTopicSub
        -        
            application_module_name: SystemGatewayModule
            topic_name: SystemGatewayTopic
            subscription_name: SystemGatewayTopicSub
        -
            application_module_name: WorkflowModule
            topic_name: WorkflowTopic
            subscription_name: WorkflowTopicSub
        -
            application_module_name: BillingModule
            topic_name: GenericTopic
            subscription_name: BillingGenericSub
        -
            application_module_name: IncidentModule
            topic_name: GenericTopic
            subscription_name: IncidentGenericSub
        -
            application_module_name: IntegrationModule
            topic_name: GenericTopic
            subscription_name: IntegrationGenericSub
        -
            application_module_name: InventoryModule
            topic_name: GenericTopic
            subscription_name: InventoryGenericSub
        -
            application_module_name: LoggingModule
            topic_name: GenericTopic
            subscription_name: LoggingGenericSub
        -
            application_module_name: NotificationModule
            topic_name: GenericTopic
            subscription_name: NotificationGenericSub
        -
            application_module_name: SystemGatewayModule
            topic_name: GenericTopic
            subscription_name: SystemGatewayGenericSub
        -
            application_module_name: WorkflowModule
            topic_name: GenericTopic
            subscription_name: WorkflowGenericSub

# Common configuration shared between all applications
configserver:
    name: Local JHipster Registry
    status: Connected to the JHipster Registry running against GitHub dev profile