spring:
    application:
        name: BillingModule

jhipster:        
    registry:
        password: admin
        
management:
    context-path: /management
    
#management:
#  context-path: /management
  
#                
# This configuration is the same for all the modules at the moment                
#
application:
    restTemplateConfig:
        readTimeout: 350
        connectTimeout: 550
    
googlepubsub:
    enabled: true;